### ISSUE TITLE
Data not appearing on the Sports England activity timetable

### ISSUE THREAD

**Issue by jennet** [goteamup/opendata#1]
I'm not sure if this is for all TeamUp sessions or just ours (Bristol Co-operative Gym) but even though [TeamUp is listed on the class management OpenActive page](https://guides.imin.co/live-streaming/how-to-set-up-for-live-streaming/getting-your-class-out-there/systems-on-offer), and TeamUp support have confirmed that our classes are definitely on the [feed](https://goteamup.com/api/openactive/v1/scheduledsessions) - the activities do not appear on the timetable.

I have raised an issue with SportsEngland for them to check, but this is also worth checking to see if any other accounts that have enabled OpenActive successfully appear on the timetable - in case it's a technical issue with the feed publication 

Cheers!

**Comment by pegler** [comment]
Hi there. As you said, the data is correctly being included in our public OpenActive feeds. We don't control which classes Sport England chooses to include in their systems, so you'll need to check with them.
